name: PeNet.Asn1
on:
  push:
    branches:
      - master
      - devel
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - devel



jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test
      
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs:
    #   - build-test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Get Version
        uses: jannemattila/get-version-from-tag@v1

      - name: Print Version
        run: |
          VERSION=$(echo "${{ steps.get_version.outputs.version }}")
          echo $VERSION

      - name: Replace Version
        run: sed -i 's|<Version>0.0.0</Version>|'"${{ steps.get_version.outputs.version }}"'|' ./src/PeNet.Asn1/PeNet.Asn1.csproj

      - name: Package
        run: dotnet pack -o artifacts
      
      # - name: Publish
      #   run: dotnet nuget push artifacts/*.nupkg -k $secrets.NUGET_API_KEY